(cl:defpackage turtle_actionlib-msg
  (:use )
  (:export
   "<VELOCITY>"
   "VELOCITY"
   "<SHAPERESULT>"
   "SHAPERESULT"
   "<SHAPEACTIONRESULT>"
   "SHAPEACTIONRESULT"
   "<SHAPEFEEDBACK>"
   "SHAPEFEEDBACK"
   "<SHAPEGOAL>"
   "SHAPEGOAL"
   "<SHAPEACTIONFEEDBACK>"
   "SHAPEACTIONFEEDBACK"
   "<SHAPEACTION>"
   "SHAPEACTION"
   "<SHAPEACTIONGOAL>"
   "SHAPEACTIONGOAL"
  ))

