(cl:defpackage nodelet-srv
  (:use )
  (:export
   "NODELETLOAD"
   "<NODELETLOAD-REQUEST>"
   "NODELETLOAD-REQUEST"
   "<NODELETLOAD-RESPONSE>"
   "NODELETLOAD-RESPONSE"
   "NODELETUNLOAD"
   "<NODELETUNLOAD-REQUEST>"
   "NODELETUNLOAD-REQUEST"
   "<NODELETUNLOAD-RESPONSE>"
   "NODELETUNLOAD-RESPONSE"
   "NODELETLIST"
   "<NODELETLIST-REQUEST>"
   "NODELETLIST-REQUEST"
   "<NODELETLIST-RESPONSE>"
   "NODELETLIST-RESPONSE"
  ))

